### ISSUE TITLE
How it works?

### ISSUE THREAD

**Issue by javthon** [rushilsingh/twitter#3]

**Comment by rushilsingh** [comment]
Hi. I have not integrated regular login into this app. You can use it if you have a twitter developer account by filling your credentials and keys in credentials to json in this format:
{
    "screen_name": "therushilsingh",
    "consumer_key":"xyz",
    "consumer_secret":"xyz",
    "access_token_key": "xyz",
    "access_token_secret": "xyz"
}
Then, to run:
make prepare-venv
python manipulate_tweets.py delete
python manipulate_tweets.py unlike

I hope this helps. Please get back to me if you have questions. Thanks for visiting @javthon !

**Comment by javthon** [comment]
Great, it worked, thx
